export enum SystemRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CASUAL = 'CASUAL',
  CONTRACT = 'CONTRACT',
}

export enum EmployeeStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum NotificationType {
  ACCOUNT_INVITE = 'ACCOUNT_INVITE',
  PASSWORD_RESET = 'PASSWORD_RESET',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',
  DEPARTMENT_CHANGED = 'DEPARTMENT_CHANGED',
  GROUP_ADDED = 'GROUP_ADDED',
  GROUP_REMOVED = 'GROUP_REMOVED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
  EMPLOYEE_ARCHIVED = 'EMPLOYEE_ARCHIVED',
  EMPLOYEE_REACTIVATED = 'EMPLOYEE_REACTIVATED',
  SCHEDULE_PUBLISHED = 'SCHEDULE_PUBLISHED',
  SCHEDULE_UNPUBLISHED = 'SCHEDULE_UNPUBLISHED',
  SCHEDULE_AMENDED = 'SCHEDULE_AMENDED',
  SCHEDULE_VIEW_REMINDER = 'SCHEDULE_VIEW_REMINDER',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  LEAVE_REJECTED = 'LEAVE_REJECTED',
  LEAVE_NUDGE = 'LEAVE_NUDGE',
  LEAVE_ESCALATED = 'LEAVE_ESCALATED',
  EMPLOYEE_JOINED = 'EMPLOYEE_JOINED',
  MISSING_EMPLOYEES = 'MISSING_EMPLOYEES',
  ALL_CLEAR = 'ALL_CLEAR',
}

export enum LeaveRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum LeaveReason {
  SICK = 'SICK',
  PERSONAL = 'PERSONAL',
  VACATION = 'VACATION',
  OTHER = 'OTHER',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  ARCHIVE = 'ARCHIVE',
  REACTIVATE = 'REACTIVATE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PASSWORD_RESET = 'PASSWORD_RESET',
  INVITE_SENT = 'INVITE_SENT',
  PUBLISH = 'PUBLISH',
  UNPUBLISH = 'UNPUBLISH',
  COPY = 'COPY',
}

export enum ScheduleVisibility {
  OWN_ONLY = 'OWN_ONLY',
  SAME_DEPARTMENT = 'SAME_DEPARTMENT',
  ALL = 'ALL',
}

export enum MidYearJoinPolicy {
  FULL_ALLOCATION = 'FULL_ALLOCATION',
  PRORATED = 'PRORATED',
}

export enum LocationStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum ScheduleStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
}

export enum DayOfWeek {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}
